litellm_settings:
    ssl_verify: false
    success_callback: ["langfuse"]

model_list:
  - model_name: nvidia/llama-3.3-70b-instruct # Custom alias
    litellm_params:
      model: "nvidia_nim/meta/llama-3.3-70b-instruct"  # e.g., "meta/llama-3.1-70b-instruct"
      api_key: "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"
      api_base: "https://integrate.api.nvidia.com/v1"
      max_tokens: 6000  # Mandatory for NVIDIA API :cite[10]
      temperature: 0.2

  - model_name: gpt120b # Custom alias
    litellm_params:
      model: "nvidia_nim/openai/gpt-oss-120b"  # e.g., "meta/llama-3.1-70b-instruct"
      api_key: "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"
      api_base: "https://integrate.api.nvidia.com/v1"
      max_tokens: 6000  # Mandatory for NVIDIA API :cite[10]
      temperature: 0.2

  - model_name: "llama3"  # Your friendly name for the model
    litellm_params:
      model: "nvidia_nim/meta/llama-3.3-70b-instruct"  # <- THE KEY! Forces the correct template
      api_key: "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"
      api_base: "https://integrate.api.nvidia.com/v1"
      # Critical inference parameters for MCP tool calling
      temperature: 0.1              # Low temp for deterministic JSON output
      top_p: 0.7                    # Focused sampling
      max_tokens: 6000              # Sufficient for complex tool responses
      stop: ["<|eot_id|>"]          # MOST IMPORTANT: Stop sequence for Llama 3.3
      # Optional but recommended parameters
      frequency_penalty: 0.0
      presence_penalty: 0.0
      stream: false                  # Set to true if you want streaming responses

      # NIM-specific parameters (if needed)
      # extra_body: {
      #   "temperature": 0.1,
      #   "top_k": 40
      # }

  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/gpt-3.5-turbo
      api_base: https://ai-openai-ds.openai.azure.com/openai/deployments/gpt-35-turbo/
      api_version: "2025-01-01-preview"
      api_key: os.environ/AZURE_API_KEY
